### ISSUE TITLE
不过盾配置，容器将无法启动

### ISSUE THREAD

**Issue by kotlef** [cockroachai/ja3-proxy#1]
docker-compose.yml 

```
services:
  ja3-proxy:
    image: xyhelper/ja3-proxy:latest
    ports:
      - "19966:9988" # JA3端口
    environment:
      WEBSITE_URL: "https://chat.openai.com/"
      PROXY: ""  
      CLIENTKEY: "" 
      LOCALPROXYUSER: "bxj58bwc" 
      LOCALPROXYPASS: "dg8ypr75b6km" 
```

<img width="1189" alt="image" src="https://github.com/cockroachai/ja3-proxy/assets/239463/95ab7b7e-caf3-44ba-8566-a040592beb48">
